// <auto-generated />
using System;
using Humans.Holded.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Humans.Holded.Data.Migrations
{
    [DbContext(typeof(HoldedDbContext))]
    [Migration("20260810201914_InitialHoldedSection")]
    partial class InitialHoldedSection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Humans.Holded.Domain.HoldedAccount", b =>
                {
                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Group")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("HoldedId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Instant>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Number");

                    b.ToTable("holded_accounts", (string)null);
                });

            modelBuilder.Entity("Humans.Holded.Domain.HoldedApiCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int?>("RateLimitRemaining")
                        .HasColumnType("integer");

                    b.Property<string>("RateLimitWindow")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CalledAt");

                    b.ToTable("holded_api_calls", (string)null);
                });

            modelBuilder.Entity("Humans.Holded.Domain.HoldedLedgerLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccountNum")
                        .HasColumnType("integer");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Instant>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntryNumber")
                        .HasColumnType("integer");

                    b.Property<Instant>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Line")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AccountNum");

                    b.HasIndex("EntryNumber", "Line")
                        .IsUnique();

                    b.ToTable("holded_ledger_lines", (string)null);
                });

            modelBuilder.Entity("Humans.Holded.Domain.HoldedSyncState", b =>
                {
                    b.Property<string>("Kind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("LastCount")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Instant?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Kind");

                    b.ToTable("holded_sync_states", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
