// <auto-generated />
using System;
using Humans.Workgroups.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Humans.Workgroups.Data.Migrations
{
    [DbContext(typeof(WorkgroupsDbContext))]
    partial class WorkgroupsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Humans.Workgroups.Domain.Workgroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AppliedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Deliverable")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DeliverableKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DiscordChannelUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DormantReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Instant?>("DormantSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DriveFolderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Instant?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Reasons")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Instant?>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<LocalDate?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DriveFolderId")
                        .IsUnique()
                        .HasFilter("\"DriveFolderId\" IS NOT NULL");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("workgroups", (string)null);
                });

            modelBuilder.Entity("Humans.Workgroups.Domain.WorkgroupDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommentCategories")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Instant?>("CommentsCloseAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("CommentsOpenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Disposition")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Instant?>("DispositionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DispositionByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DispositionNote")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkgroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasFilter("\"CreatedByUserId\" IS NOT NULL");

                    b.HasIndex("WorkgroupId", "Status");

                    b.ToTable("workgroup_documents", (string)null);
                });

            modelBuilder.Entity("Humans.Workgroups.Domain.WorkgroupDocumentComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("HiddenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HiddenByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("HiddenReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Instant?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RespondedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Response")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId")
                        .HasFilter("\"AuthorUserId\" IS NOT NULL");

                    b.HasIndex("DocumentId", "Category");

                    b.ToTable("workgroup_document_comments", (string)null);
                });

            modelBuilder.Entity("Humans.Workgroups.Domain.WorkgroupLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasMaxLength(16000)
                        .HasColumnType("character varying(16000)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<LocalDate>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<Guid?>("SurveyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkgroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId")
                        .HasFilter("\"AuthorUserId\" IS NOT NULL");

                    b.HasIndex("DocumentId");

                    b.HasIndex("WorkgroupId", "OccurredOn");

                    b.ToTable("workgroup_log_entries", (string)null);
                });

            modelBuilder.Entity("Humans.Workgroups.Domain.WorkgroupMeeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("EndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LocationUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Minutes")
                        .HasColumnType("text");

                    b.Property<Instant>("StartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkgroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasFilter("\"CreatedByUserId\" IS NOT NULL");

                    b.HasIndex("WorkgroupId", "StartUtc");

                    b.ToTable("workgroup_meetings", (string)null);
                });

            modelBuilder.Entity("Humans.Workgroups.Domain.WorkgroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkgroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkgroupId", "UserId")
                        .IsUnique()
                        .HasFilter("\"LeftAt\" IS NULL");

                    b.ToTable("workgroup_members", (string)null);
                });

            modelBuilder.Entity("Humans.Workgroups.Domain.WorkgroupDocument", b =>
                {
                    b.HasOne("Humans.Workgroups.Domain.Workgroup", "Workgroup")
                        .WithMany("Documents")
                        .HasForeignKey("WorkgroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workgroup");
                });

            modelBuilder.Entity("Humans.Workgroups.Domain.WorkgroupDocumentComment", b =>
                {
                    b.HasOne("Humans.Workgroups.Domain.WorkgroupDocument", "Document")
                        .WithMany("Comments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Humans.Workgroups.Domain.WorkgroupLogEntry", b =>
                {
                    b.HasOne("Humans.Workgroups.Domain.WorkgroupDocument", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Humans.Workgroups.Domain.Workgroup", "Workgroup")
                        .WithMany("LogEntries")
                        .HasForeignKey("WorkgroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Workgroup");
                });

            modelBuilder.Entity("Humans.Workgroups.Domain.WorkgroupMeeting", b =>
                {
                    b.HasOne("Humans.Workgroups.Domain.Workgroup", "Workgroup")
                        .WithMany("Meetings")
                        .HasForeignKey("WorkgroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workgroup");
                });

            modelBuilder.Entity("Humans.Workgroups.Domain.WorkgroupMember", b =>
                {
                    b.HasOne("Humans.Workgroups.Domain.Workgroup", "Workgroup")
                        .WithMany("Members")
                        .HasForeignKey("WorkgroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workgroup");
                });

            modelBuilder.Entity("Humans.Workgroups.Domain.Workgroup", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("LogEntries");

                    b.Navigation("Meetings");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Humans.Workgroups.Domain.WorkgroupDocument", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
