using Humans.Base.Interfaces;
using NodaTime;

namespace Humans.Budget.Contracts;

/// <summary>
/// Cross-section read surface for the Budget section. External sections and the two
/// Base consumers inject this interface; it exposes the active year's projection, one
/// category lookup, the coordinator's team set and the summary computation — no EF
/// entities, no writes. See <c>memory/architecture/section-read-write-split.md</c>.
/// </summary>
/// <remarks>
/// The section's own controllers take the internal <c>BudgetService</c> directly, so the
/// other ~36 members of the old <c>IBudgetService</c> — year/group/category/line-item
/// CRUD, the audit log, the cash-flow and VAT projections, the ticketing projection
/// parameters — are not public at all (design §15 step 5).
/// </remarks>
public interface IBudgetServiceRead : IApplicationService
{
    /// <summary>
    /// The active budget year with its full group → category → line item projection,
    /// or null when no year is active.
    /// </summary>
    Task<BudgetYearDetail?> GetActiveYearAsync();

    /// <summary>
    /// One budget year by id, same projection as <see cref="GetActiveYearAsync"/>. Expenses
    /// reads this to offer the categories of the year a pending report is already booked to,
    /// which is not always the active one.
    /// </summary>
    Task<BudgetYearDetail?> GetYearByIdAsync(Guid id);

    /// <summary>
    /// One budget category with its group, year and line items. Expenses reads this to
    /// resolve the category an expense report is booked against.
    /// </summary>
    Task<BudgetCategorySnapshot?> GetCategoryByIdAsync(Guid id);

    /// <summary>
    /// The team ids the user coordinates a budget for, including teams inherited through
    /// the team hierarchy.
    /// </summary>
    Task<HashSet<Guid>> GetEffectiveCoordinatorTeamIdsAsync(Guid userId);

    /// <summary>
    /// Income/expense totals and categorical breakdowns for an already-loaded set of
    /// groups. Pure computation over the argument — no I/O.
    /// </summary>
    BudgetSummaryResult ComputeBudgetSummary(IReadOnlyList<BudgetGroupDetail> groups);
}

/// <summary>
/// Full budget-year projection (year → groups → categories → line items) used by the
/// Budget, Expenses, Finance and Tickets presentation flows. Replaces direct exposure of
/// the <c>BudgetYear</c> EF entity.
/// </summary>
public sealed record BudgetYearDetail(
    Guid Id,
    string Year,
    string Name,
    BudgetYearStatus Status,
    bool IsDeleted,
    IReadOnlyList<BudgetGroupDetail> Groups);

public sealed record BudgetGroupDetail(
    Guid Id,
    Guid BudgetYearId,
    string Name,
    int SortOrder,
    bool IsRestricted,
    bool IsDepartmentGroup,
    bool IsTicketingGroup,
    TicketingProjectionSnapshot? TicketingProjection,
    IReadOnlyList<BudgetCategoryDetail> Categories);

public sealed record BudgetCategoryDetail(
    Guid Id,
    Guid BudgetGroupId,
    string Name,
    decimal AllocatedAmount,
    ExpenditureType ExpenditureType,
    Guid? TeamId,
    int SortOrder,
    IReadOnlyList<BudgetLineItemDetail> LineItems);

public sealed record BudgetLineItemDetail(
    Guid Id,
    Guid BudgetCategoryId,
    string Description,
    decimal Amount,
    Guid? ResponsibleTeamId,
    string? Notes,
    LocalDate? ExpectedDate,
    int VatRate,
    bool IsAutoGenerated,
    bool IsCashflowOnly,
    int SortOrder);

public sealed record TicketingProjectionSnapshot(
    Guid Id,
    Guid BudgetGroupId,
    LocalDate? StartDate,
    LocalDate? EventDate,
    int InitialSalesCount,
    decimal DailySalesRate,
    decimal AverageTicketPrice,
    int VatRate,
    decimal StripeFeePercent,
    decimal StripeFeeFixed,
    decimal TicketTailorFeePercent,
    Instant CreatedAt,
    Instant UpdatedAt);

public sealed record BudgetCategorySnapshot(
    Guid Id,
    Guid BudgetGroupId,
    string Name,
    decimal AllocatedAmount,
    ExpenditureType ExpenditureType,
    Guid? TeamId,
    int SortOrder,
    BudgetCategoryGroupSnapshot? BudgetGroup,
    IReadOnlyList<BudgetCategoryLineItemSnapshot> LineItems);

public sealed record BudgetCategoryGroupSnapshot(
    Guid Id,
    Guid BudgetYearId,
    string Name,
    bool IsRestricted,
    bool IsTicketingGroup,
    BudgetCategoryYearSnapshot? BudgetYear);

public sealed record BudgetCategoryYearSnapshot(
    Guid Id,
    string Year,
    string Name,
    bool IsDeleted);

public sealed record BudgetCategoryLineItemSnapshot(
    Guid Id,
    Guid BudgetCategoryId,
    string Description,
    decimal Amount,
    Guid? ResponsibleTeamId,
    string? ResponsibleTeamName,
    string? Notes,
    LocalDate? ExpectedDate,
    int VatRate,
    bool IsAutoGenerated,
    bool IsCashflowOnly,
    int SortOrder);

/// <summary>
/// Computed budget summary with income/expense totals and categorical breakdowns.
/// Produced by <see cref="IBudgetServiceRead.ComputeBudgetSummary"/> from in-memory group data.
/// </summary>
public sealed class BudgetSummaryResult
{
    public decimal TotalIncome { get; init; }
    public decimal TotalExpenses { get; init; }
    public decimal NetBalance { get; init; }
    public required IReadOnlyList<BudgetSliceResult> IncomeSlices { get; init; }
    public required IReadOnlyList<BudgetSliceResult> ExpenseSlices { get; init; }
}

public sealed class BudgetSliceResult
{
    public required string Name { get; init; }
    public decimal Amount { get; init; }
    public decimal Percentage { get; init; }
}
