namespace Humans.AuditLog.Contracts;

/// <summary>
/// Actions that can be recorded in the audit log.
/// Stored as string in DB; new values can be appended without migration.
/// </summary>
public enum AuditAction
{
    TeamMemberAdded,
    TeamMemberRemoved,
    MemberSuspended,
    MemberUnsuspended,
    AccountAnonymized,
    RoleAssigned,
    RoleEnded,
    VolunteerApproved,
    GoogleResourceAccessGranted,
    GoogleResourceAccessRevoked,
    GoogleResourceProvisioned,
    TeamJoinedDirectly,
    TeamLeft,
    TeamJoinRequestApproved,
    TeamJoinRequestRejected,
    TeamMemberRoleChanged,
    AnomalousPermissionDetected,
    MembershipsRevokedOnDeletionRequest,
    ConsentCheckCleared,
    ConsentCheckFlagged,
    SignupRejected,
    TierApplicationApproved,
    TierApplicationRejected,
    TierDowngraded,
    GoogleResourceDeactivated,
    FacilitatedMessageSent,
    TeamRoleDefinitionCreated,
    TeamRoleDefinitionUpdated,
    TeamRoleDefinitionDeleted,
    TeamRoleAssigned,
    TeamRoleUnassigned,
    CampCreated,
    CampUpdated,
    CampDeleted,
    CampSeasonCreated,
    CampSeasonApproved,
    CampSeasonRejected,
    CampSeasonWithdrawn,
    CampSeasonStatusChanged,
    CampNameChanged,
    CampLeadAdded,
    CampLeadRemoved,
    CampPrimaryLeadTransferred,
    CampImageUploaded,
    CampImageDeleted,
    ShiftSignupConfirmed,
    ShiftSignupRefused,
    ShiftSignupVoluntold,
    ShiftSignupBailed,
    ShiftSignupNoShow,
    ShiftSignupCancelled,
    TeamPageContentUpdated,
    FeedbackResponseSent,
    FeedbackStatusChanged,
    WorkspaceAccountProvisioned,
    WorkspaceAccountSuspended,
    WorkspaceAccountReactivated,
    WorkspaceAccountPasswordReset,
    WorkspaceAccountLinked,
    WorkspaceAccountBackupCodesGenerated,
    // Reserved — was wired briefly during PR #254 development. No code path
    // currently writes this value; do not remove (audit enum is positional).
    WorkspaceAccountBackupCodesInvalidated,
    WorkspaceAccountResetBlockedFor2Sv,
    AccountMergeRequested,
    AccountMergeAccepted,
    AccountMergeRejected,
    GoogleResourceSettingsRemediated,
    CommunicationPreferenceChanged,
    ContactCreated,
    RotaMovedToTeam,
    GoogleResourceInheritanceDriftCorrected,
    FeedbackAssignmentChanged,
    GoogleEmailRenamed,
    CalendarEventCreated,
    CalendarEventUpdated,
    CalendarEventDeleted,
    CalendarOccurrenceCancelled,
    CalendarOccurrenceOverridden,
    CampMemberRequested,
    CampMemberApproved,
    CampMemberRejected,
    CampMemberWithdrawn,
    CampMemberLeft,
    CampMemberRemoved,
    CampMemberAddedByLead,
    CampRoleDefinitionCreated,
    CampRoleDefinitionUpdated,
    CampRoleDefinitionDeactivated,
    CampRoleDefinitionReactivated,
    CampRoleAssigned,
    CampRoleUnassigned,
    IssueStatusChanged,
    IssueAssigneeChanged,
    IssueSectionChanged,
    IssueGitHubLinked,
    AccountPurged,
    UserEmailProviderBackfilled,
    UserEmailGoogleSet,
    UserEmailGoogleCleared,
    UserEmailLinked,
    UserEmailUnlinked,
    UserEmailPrimarySet,
    UserEmailPrimaryCleared,
    UserEmailDeleted,
    UserEmailVisibilityChanged,
    UserEmailAdded,
    UserEmailManuallyVerified,
    ShiftSignupCreated,
    ShiftSignupReassigned,
    StoreOrderCreated,
    StoreOrderDeleted,
    StoreLineAdded,
    StoreLineRemoved,
    StoreCounterpartyEdited,
    StoreProductCreated,
    StoreProductUpdated,
    StoreProductPriceChanged,
    StoreProductDeactivated,
    StoreInvoiceIssued,
    StorePaymentRecorded,
    StorePaymentSettled,
    StorePaymentFailed,
    StorePaymentExpired,
    TicketTransferRequested,
    TicketTransferApproved,
    TicketTransferRejected,
    TicketTransferCancelled,
    TicketTransferAutoFailed,
    OrphanUserEmailDeleted,
    GhostExternalLoginsDeleted,
    LegacyIdentityEmailBackfilled,
    CampEarlyEntryGranted,
    CampEarlyEntryRevoked,
    CampSeasonEeSlotCountChanged,
    CampSettingsEeStartDateChanged,
    ExpenseSubmit,
    ExpenseEndorse,
    ExpenseCoordinatorReject,
    ExpenseApprove,
    ExpenseReject,
    ExpenseWithdraw,
    ExpenseCategoryOverride,
    ExpenseSepaSent,
    ExpenseSepaReopened,
    ExpensePaid,
    IbanSet,
    IbanRemove,
    IbanReveal,
    ExpenseAttachmentUploaded,
    ExpenseAttachmentRemoved,
    VolunteerCampSetupSet,
    VolunteerCampSetupCleared,
    // Reserved — was wired during the first volunteer-tracking day-off
    // iteration (renamed in the redesign; historical audit rows may still
    // exist on dev DBs). Do not remove (audit enum is positional).
    VolunteerDayBlocked,
    VolunteerDayUnblocked,
    VolunteerOwnBlockedDaysSaved,
    VolunteerDayOffMarked,
    VolunteerDayOffCleared,
    // Issue nobodies-collective/Humans#697: OAuth-callback reconcile audits.
    OAuthRenameCollision,
    OAuthRenameCollisionBlocked,
    UserEmailDisplacedByOAuthRename,
    MailerLiteReconciliationCompleted,
    MailerLiteAudienceSyncCompleted,
    GoogleSyncRetryScheduled,
    TicketContactsImported,
    ContainerCreated,
    ContainerUpdated,
    ContainerDeleted,
    ContainerPlacementSaved,
    ContainerPlacementCleared,
    ContainerPlacementNotesUpdated,
    CoordinatorRotaMessageSent,
    CoordinatorTeamRotasMessageSent,
    // Coordinator edits a volunteer's declared build availability on their behalf
    // (Profile build strip).
    VolunteerAvailabilitySet,
    VolunteerAvailabilityCleared,
    EarlyEntryGranted,
    EarlyEntryUpdated,
    EarlyEntryRevoked,
    StorePaymentsReconciled,
    GateTerminalPasswordSet,
    // Gate personal-PIN lifecycle: who set (self-enrol or admin) or reset a staffer's claim PIN.
    GateStaffPinSet,
    GateStaffPinReset,
    SurveyCreated,
    SurveyUpdated,
    SurveyOpened,
    SurveyClosed,
    SurveyInvitesSent,
    SurveyReminderSent,
    // Holded expense push outcomes (nobodies-collective/Humans#1045). Written by the outbox
    // drain so the per-report history survives outbox-row cleanup, which the outbox columns
    // themselves do not.
    ExpenseHoldedPushed,
    ExpenseHoldedFailed,
    ExpenseHoldedRequeued,
    // Backdoor personal machine-API key lifecycle (nobodies-collective/Humans#1128).
    // Rotation is recorded as a revoke of the old key followed by an issue of the new one.
    BackdoorApiKeyIssued,
    BackdoorApiKeyRevoked,
    // Linking a feedback report to a GitHub issue — the last Feedback mutation that
    // recorded no actor (nobodies-collective/Humans#1128).
    FeedbackGitHubLinked,
    // Filing an issue through the machine API, where the filer and the reporter can differ
    // (nobodies-collective/Humans#1128). The in-app reporter is their own filer, so that path
    // still records creation on the issue row alone.
    IssueCreated,
    // One per credit transfer in a generated SEPA payout file (nobodies-collective/Humans#1134).
    // Written by Finance; the IBAN in the description is always masked.
    SepaPayoutTransfer,
    // One per transfer booked into Holded from /Finance/Sepa (nobodies-collective/Humans#1141).
    // Same entity type as the generation entry; the IBAN in the description is always masked.
    SepaPayoutTransferBooked,

    // City Planning settings writes. These decide who may move barrios and containers on the
    // site map and what the published ground truth is, and every one of them is an organiser
    // acting on the members' behalf. The settings row records when a phase changed but not
    // who changed it, so the actor lives here.
    CityPlanningPlacementOpened,
    CityPlanningPlacementClosed,
    CityPlanningContainerPlacementOpened,
    CityPlanningContainerPlacementClosed,
    CityPlanningLimitZoneUpdated,
    CityPlanningLimitZoneDeleted,
    CityPlanningOfficialZonesUpdated,
    CityPlanningOfficialZonesDeleted,

    // A finance admin filed an expense report for another member. Self-created drafts are not
    // audited — only the on-behalf case, which names the actor and the member.
    ExpenseCreatedOnBehalf,
    // A finance admin changed somebody else's report — header, or a line added/edited/removed.
    // One action for all of them; the description says what changed. Self-edits are not audited.
    ExpenseEditedOnBehalf,
    // The payee IBAN snapshot on a submitted (not yet approved) report was refreshed from the
    // report's own IBAN page. Entity is the report so it shows in that report's history; the
    // IBAN is unmasked when somebody set it for another member (memory/code/audit-pii-subject-allowed.md).
    ExpensePayeeIbanUpdated,
}
