using Humans.Domain.Entities;
using Humans.Infrastructure.Data.Configurations.Tickets;
using Microsoft.EntityFrameworkCore;

namespace Humans.Infrastructure.Data;

/// <summary>
/// Per-section database context for the Tickets section
/// (nobodies-collective/Humans#858): maps only <c>ticket_orders</c>,
/// <c>ticket_attendees</c>, <c>ticket_sync_state</c> and
/// <c>ticket_transfer_requests</c>, with its own
/// <c>__EFMigrationsHistory_Tickets</c> table and migrations under
/// <c>Migrations/Tickets/</c>. Same database, same connection — the split is a
/// code-side partition of the EF model.
/// </summary>
/// <remarks>
/// Internal-sealed like every section context (issue #750): repositories
/// are the only consumers. Configurations are applied explicitly (not by
/// assembly scanning) so this model can never accrete another section's tables.
/// Purchasers and matched attendees are bare Guid references, so the Identity
/// tables stay in <see cref="UsersDbContext"/> and are deliberately absent
/// here; the Budget-owned <c>ticketing_projections</c> table is likewise
/// absent. <c>TicketSyncState</c> carries a model-level <c>HasData</c>
/// singleton with an identity int PK, both regenerated by the baseline.
/// </remarks>
internal sealed class TicketsDbContext(DbContextOptions<TicketsDbContext> options)
    : DbContext(options)
{
    public DbSet<TicketOrder> TicketOrders => Set<TicketOrder>();
    public DbSet<TicketAttendee> TicketAttendees => Set<TicketAttendee>();
    public DbSet<TicketSyncState> TicketSyncStates => Set<TicketSyncState>();
    public DbSet<TicketTransferRequest> TicketTransferRequests => Set<TicketTransferRequest>();

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);

        builder.ApplyConfiguration(new TicketOrderConfiguration());
        builder.ApplyConfiguration(new TicketAttendeeConfiguration());
        builder.ApplyConfiguration(new TicketSyncStateConfiguration());
        builder.ApplyConfiguration(new TicketTransferRequestConfiguration());
    }
}
