// <auto-generated />
using System;
using Humans.Base.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Humans.GoogleIntegration.Data.Migrations
{
    [DbContext(typeof(GoogleIntegrationDbContext))]
    [Migration("20260809125108_BaselineGoogleIntegration")]
    partial class BaselineGoogleIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Humans.Domain.Entities.GoogleResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DrivePermissionLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Instant?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Instant>("ProvisionedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RestrictInheritedAccess")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("GoogleId");

                    b.HasIndex("IsActive");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamId", "GoogleId")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("google_resources", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.GoogleSyncOutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("FailedPermanently")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeduplicationKey")
                        .IsUnique();

                    b.HasIndex("ProcessedAt", "OccurredAt");

                    b.HasIndex("TeamId", "UserId", "ProcessedAt");

                    b.ToTable("google_sync_outbox", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.SyncServiceSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SyncMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceType")
                        .IsUnique();

                    b.ToTable("sync_service_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            ServiceType = "GoogleDrive",
                            SyncMode = "None",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17730144000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            ServiceType = "GoogleGroups",
                            SyncMode = "None",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17730144000000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            ServiceType = "Discord",
                            SyncMode = "None",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17730144000000000L)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
