<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sections\Humans.Holded\Humans.Holded.csproj" />
    <ProjectReference Include="..\..\src\Sections\Humans.Finance.Contracts\Humans.Finance.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Sections\Humans.Holded.Contracts\Humans.Holded.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Sections\Humans.Shifts.Contracts\Humans.Shifts.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Humans.Base\Humans.Base.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="NodaTime.Testing" />
  </ItemGroup>

</Project>
