using Humans.Teams.Contracts;
using Humans.Budget.Contracts;
using NodaTime;

namespace Humans.Budget.Services;

/// <summary>
/// Budget's section-internal projections. Everything here is consumed only by the
/// section's own controllers, views and jobs; the shapes other sections read live on
/// <c>Humans.Budget.Contracts</c> instead (design §15.5b).
/// </summary>
internal sealed record BudgetYearSummarySnapshot(
    Guid Id,
    string Year,
    string Name,
    BudgetYearStatus Status,
    bool IsDeleted,
    IReadOnlyList<BudgetGroupSummarySnapshot> Groups);

internal sealed record BudgetGroupSummarySnapshot(
    Guid Id,
    string Name,
    int SortOrder,
    bool IsRestricted,
    bool IsDepartmentGroup);

internal sealed record BudgetLineItemSnapshot(
    Guid Id,
    Guid BudgetCategoryId,
    string Description,
    decimal Amount,
    Guid? ResponsibleTeamId,
    string? Notes,
    LocalDate? ExpectedDate,
    int VatRate,
    bool IsAutoGenerated,
    bool IsCashflowOnly,
    int SortOrder);

internal sealed record BudgetAuditLogSnapshot(
    Guid Id,
    Guid BudgetYearId,
    string EntityType,
    Guid EntityId,
    string? FieldName,
    string? OldValue,
    string? NewValue,
    string Description,
    Guid ActorUserId,
    Instant OccurredAt);

internal sealed record CoordinatorBudgetViewData(
    BudgetYearDetail? Year,
    HashSet<Guid> EditableTeamIds,
    bool IsFinanceAdmin,
    bool ShouldRedirectToSummary);

internal sealed record CoordinatorCategoryDetailViewData(
    BudgetCategorySnapshot? Category,
    bool ShouldForbid,
    IReadOnlyList<TeamInfo> Teams);

internal sealed record EnsureTicketingGroupResult(bool Created, string Message);

/// <summary>
/// A synthetic VAT cash flow entry computed from a line item with VatRate &gt; 0.
/// Amount is signed: negative = expense (VAT liability from income), positive = income
/// (VAT credit from expenses). SettlementDate is ~45 days after the quarter end containing
/// the source item's ExpectedDate.
/// </summary>
internal sealed class VatCashFlowEntry
{
    public required string CategoryName { get; init; }
    public decimal Amount { get; init; }
    public required LocalDate SettlementDate { get; init; }
}

/// <summary>
/// A projected week of ticket sales — virtual line items not yet materialized.
/// </summary>
internal sealed class TicketingWeekProjection
{
    public required string WeekLabel { get; init; }
    public LocalDate WeekStart { get; init; }
    public LocalDate WeekEnd { get; init; }
    public int ProjectedTickets { get; init; }
    public decimal ProjectedRevenue { get; init; }
    public decimal ProjectedStripeFees { get; init; }
    public decimal ProjectedTtFees { get; init; }
}

/// <summary>
/// Aggregated ticket sales for a completed ISO week, produced by the bridge service from
/// <c>ITicketServiceRead</c> data and consumed by <c>BudgetService.SyncTicketingActualsAsync</c>.
/// </summary>
internal sealed record TicketingWeeklyActuals(
    LocalDate Monday,
    LocalDate Sunday,
    string WeekLabel,
    int TicketCount,
    decimal Revenue,
    decimal StripeFees,
    decimal TicketTailorFees);

internal sealed record TicketingProjectionUpdateCommand(
    Guid BudgetGroupId,
    Guid BudgetYearId,
    LocalDate? StartDate,
    LocalDate? EventDate,
    int InitialSalesCount,
    decimal DailySalesRate,
    decimal AverageTicketPrice,
    int VatRate,
    decimal StripeFeePercent,
    decimal StripeFeeFixed,
    decimal TicketTailorFeePercent);
