// <auto-generated />
using System;
using Humans.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Humans.Infrastructure.Migrations.Budget
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20260809142337_BaselineBudget")]
    partial class BaselineBudget
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Humans.Domain.Entities.BudgetAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetYearId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FieldName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OldValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("BudgetYearId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("budget_audit_logs", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.BudgetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AllocatedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BudgetGroupId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpenditureType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .HasFilter("\"TeamId\" IS NOT NULL");

                    b.HasIndex("BudgetGroupId", "SortOrder");

                    b.ToTable("budget_categories", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.BudgetGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetYearId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDepartmentGroup")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTicketingGroup")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BudgetYearId", "SortOrder");

                    b.ToTable("budget_groups", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.BudgetLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BudgetCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<LocalDate?>("ExpectedDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCashflowOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("ResponsibleTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VatRate")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleTeamId")
                        .HasFilter("\"ResponsibleTeamId\" IS NOT NULL");

                    b.HasIndex("BudgetCategoryId", "SortOrder");

                    b.ToTable("budget_line_items", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.BudgetYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("budget_years", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.TicketingProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageTicketPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BudgetGroupId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DailySalesRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<LocalDate?>("EventDate")
                        .HasColumnType("date");

                    b.Property<int>("InitialSalesCount")
                        .HasColumnType("integer");

                    b.Property<LocalDate?>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("StripeFeeFixed")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("StripeFeePercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("TicketTailorFeePercent")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VatRate")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BudgetGroupId")
                        .IsUnique();

                    b.ToTable("ticketing_projections", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.BudgetAuditLog", b =>
                {
                    b.HasOne("Humans.Domain.Entities.BudgetYear", "BudgetYear")
                        .WithMany("AuditLogs")
                        .HasForeignKey("BudgetYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BudgetYear");
                });

            modelBuilder.Entity("Humans.Domain.Entities.BudgetCategory", b =>
                {
                    b.HasOne("Humans.Domain.Entities.BudgetGroup", "BudgetGroup")
                        .WithMany("Categories")
                        .HasForeignKey("BudgetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetGroup");
                });

            modelBuilder.Entity("Humans.Domain.Entities.BudgetGroup", b =>
                {
                    b.HasOne("Humans.Domain.Entities.BudgetYear", "BudgetYear")
                        .WithMany("Groups")
                        .HasForeignKey("BudgetYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetYear");
                });

            modelBuilder.Entity("Humans.Domain.Entities.BudgetLineItem", b =>
                {
                    b.HasOne("Humans.Domain.Entities.BudgetCategory", "BudgetCategory")
                        .WithMany("LineItems")
                        .HasForeignKey("BudgetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetCategory");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TicketingProjection", b =>
                {
                    b.HasOne("Humans.Domain.Entities.BudgetGroup", "BudgetGroup")
                        .WithOne("TicketingProjection")
                        .HasForeignKey("Humans.Domain.Entities.TicketingProjection", "BudgetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetGroup");
                });

            modelBuilder.Entity("Humans.Domain.Entities.BudgetCategory", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("Humans.Domain.Entities.BudgetGroup", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("TicketingProjection");
                });

            modelBuilder.Entity("Humans.Domain.Entities.BudgetYear", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
