// <auto-generated />
using System;
using Humans.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Humans.Infrastructure.Migrations.Shifts
{
    [DbContext(typeof(ShiftsDbContext))]
    [Migration("20260810220204_BaselineShifts")]
    partial class BaselineShifts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Humans.Domain.Entities.EventSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BarriosEarlyEntryAllocation")
                        .HasColumnType("jsonb");

                    b.Property<int>("BuildStartOffset")
                        .HasColumnType("integer");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EarlyEntryCapacity")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Instant?>("EarlyEntryClose")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventEndOffset")
                        .HasColumnType("integer");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("FinishingWeekendStartOffset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-4);

                    b.Property<int>("FirstCrewStartOffset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-25);

                    b.Property<LocalDate>("GateOpeningDate")
                        .HasColumnType("date");

                    b.Property<int?>("GlobalVolunteerCap")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShiftBrowsingOpen")
                        .HasColumnType("boolean");

                    b.Property<int>("PreEventWeekStartOffset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-9);

                    b.Property<int>("ReminderLeadTimeHours")
                        .HasColumnType("integer");

                    b.Property<int>("SetupWeekStartOffset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-16);

                    b.Property<int>("StrikeEndOffset")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("event_settings", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.GeneralAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("AvailableDayOffsets")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventSettingsId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventSettingsId");

                    b.HasIndex("UserId", "EventSettingsId")
                        .IsUnique();

                    b.ToTable("general_availability", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.Rota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("EventSettingsId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVisibleToVolunteers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PracticalInfo")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventSettingsId", "TeamId");

                    b.ToTable("rotas", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AdminOnly")
                        .HasColumnType("boolean");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOffset")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxVolunteers")
                        .HasColumnType("integer");

                    b.Property<int>("MinVolunteers")
                        .HasColumnType("integer");

                    b.Property<Guid>("RotaId")
                        .HasColumnType("uuid");

                    b.Property<LocalTime>("StartTime")
                        .HasColumnType("time");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RotaId");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.ShiftSignup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enrolled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("EnrolledByUserId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SignupBlockId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("SignupBlockId");

                    b.HasIndex("UserId");

                    b.HasIndex("ShiftId", "Status");

                    b.ToTable("shift_signups", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.ShiftTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_shift_tags_name_unique");

                    b.ToTable("shift_tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            Name = "Heavy lifting"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            Name = "Working in the sun"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            Name = "Working in the shade"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000004"),
                            Name = "Organisational task"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000005"),
                            Name = "Meeting new people"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000006"),
                            Name = "Looking after folks"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000007"),
                            Name = "Exploring the site"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000008"),
                            Name = "Feeding and hydrating folks"
                        });
                });

            modelBuilder.Entity("Humans.Domain.Entities.VolunteerBuildStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<LocalDate?>("BarrioSetupStartDate")
                        .HasColumnType("date");

                    b.Property<string>("DayOffs")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Guid>("EventSettingsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Instant?>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SetByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventSettingsId");

                    b.HasIndex("UserId", "EventSettingsId")
                        .IsUnique();

                    b.ToTable("volunteer_build_statuses", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.VolunteerEventProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("AllergyOtherText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DietaryPreference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IntoleranceOtherText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Intolerances")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MedicalConditions")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Quirks")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("volunteer_event_profiles", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.VolunteerTagPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShiftTagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShiftTagId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ShiftTagId")
                        .IsUnique()
                        .HasDatabaseName("IX_volunteer_tag_preferences_user_tag_unique");

                    b.ToTable("volunteer_tag_preferences", (string)null);
                });

            modelBuilder.Entity("RotaShiftTag", b =>
                {
                    b.Property<Guid>("RotaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShiftTagId")
                        .HasColumnType("uuid");

                    b.HasKey("RotaId", "ShiftTagId");

                    b.HasIndex("ShiftTagId");

                    b.ToTable("rota_shift_tags", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.GeneralAvailability", b =>
                {
                    b.HasOne("Humans.Domain.Entities.EventSettings", "EventSettings")
                        .WithMany()
                        .HasForeignKey("EventSettingsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventSettings");
                });

            modelBuilder.Entity("Humans.Domain.Entities.Rota", b =>
                {
                    b.HasOne("Humans.Domain.Entities.EventSettings", "EventSettings")
                        .WithMany("Rotas")
                        .HasForeignKey("EventSettingsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventSettings");
                });

            modelBuilder.Entity("Humans.Domain.Entities.Shift", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Rota", "Rota")
                        .WithMany("Shifts")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("Humans.Domain.Entities.ShiftSignup", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Shift", "Shift")
                        .WithMany("ShiftSignups")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Humans.Domain.Entities.VolunteerBuildStatus", b =>
                {
                    b.HasOne("Humans.Domain.Entities.EventSettings", null)
                        .WithMany()
                        .HasForeignKey("EventSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Humans.Domain.Entities.VolunteerTagPreference", b =>
                {
                    b.HasOne("Humans.Domain.Entities.ShiftTag", "ShiftTag")
                        .WithMany("VolunteerPreferences")
                        .HasForeignKey("ShiftTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShiftTag");
                });

            modelBuilder.Entity("RotaShiftTag", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Rota", null)
                        .WithMany()
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Humans.Domain.Entities.ShiftTag", null)
                        .WithMany()
                        .HasForeignKey("ShiftTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Humans.Domain.Entities.EventSettings", b =>
                {
                    b.Navigation("Rotas");
                });

            modelBuilder.Entity("Humans.Domain.Entities.Rota", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Humans.Domain.Entities.Shift", b =>
                {
                    b.Navigation("ShiftSignups");
                });

            modelBuilder.Entity("Humans.Domain.Entities.ShiftTag", b =>
                {
                    b.Navigation("VolunteerPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
