// <auto-generated />
using System;
using Humans.Gate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Humans.Gate.Data.Migrations
{
    [DbContext(typeof(GateDbContext))]
    [Migration("20260810151929_BaselineGate")]
    partial class BaselineGate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Humans.Domain.Entities.GateScanEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdmitDedupeKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Instant?>("ClientScanAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuestUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LaneId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OverrideByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScannedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TicketAttendeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("AdmitDedupeKey")
                        .IsUnique()
                        .HasDatabaseName("ix_gate_scan_events_admit_dedupe_key");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("ScannedByUserId");

                    b.ToTable("gate_scan_events", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.GateSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<Instant>("GeneralEntryOpensAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinorAgeThresholdYears")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("gate_settings", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.GateStaffPin", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AdminEnrolled")
                        .HasColumnType("boolean");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("gate_staff_pins", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
