using System;
using Microsoft.EntityFrameworkCore.Migrations;
using NodaTime;

#nullable disable

namespace Humans.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddTicketingProjectionAndBudgetFlags : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "budget_line_items",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsCashflowOnly",
                table: "budget_line_items",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsTicketingGroup",
                table: "budget_groups",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.CreateTable(
                name: "ticketing_projections",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    BudgetGroupId = table.Column<Guid>(type: "uuid", nullable: false),
                    StartDate = table.Column<LocalDate>(type: "date", nullable: true),
                    EventDate = table.Column<LocalDate>(type: "date", nullable: true),
                    InitialSalesCount = table.Column<int>(type: "integer", nullable: false),
                    DailySalesRate = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    AverageTicketPrice = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    VatRate = table.Column<int>(type: "integer", nullable: false),
                    StripeFeePercent = table.Column<decimal>(type: "numeric(18,4)", precision: 18, scale: 4, nullable: false),
                    StripeFeeFixed = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    TicketTailorFeePercent = table.Column<decimal>(type: "numeric(18,4)", precision: 18, scale: 4, nullable: false),
                    CreatedAt = table.Column<Instant>(type: "timestamp with time zone", nullable: false),
                    UpdatedAt = table.Column<Instant>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ticketing_projections", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ticketing_projections_budget_groups_BudgetGroupId",
                        column: x => x.BudgetGroupId,
                        principalTable: "budget_groups",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ticketing_projections_BudgetGroupId",
                table: "ticketing_projections",
                column: "BudgetGroupId",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ticketing_projections");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "budget_line_items");

            migrationBuilder.DropColumn(
                name: "IsCashflowOnly",
                table: "budget_line_items");

            migrationBuilder.DropColumn(
                name: "IsTicketingGroup",
                table: "budget_groups");
        }
    }
}
