// <auto-generated />
using System;
using Humans.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Humans.Infrastructure.Migrations
{
    [DbContext(typeof(HumansDbContext))]
    [Migration("20260809142447_PeelCityPlanningBudgetCamps")]
    partial class PeelCityPlanningBudgetCamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Humans.Domain.Entities.AccountMergeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("PendingEmailId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("SourceUserId");

                    b.HasIndex("Status");

                    b.HasIndex("TargetUserId");

                    b.ToTable("account_merge_requests", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("SyncSource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("ResourceId");

                    b.HasIndex("EntityType", "EntityId");

                    b.HasIndex("RelatedEntityType", "RelatedEntityId");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.CommunicationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("InboxEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("OptedOut")
                        .HasColumnType("boolean");

                    b.Property<Instant?>("SubscribedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SubscribedAt");

                    b.Property<string>("UpdateSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Category")
                        .IsUnique();

                    b.ToTable("communication_preferences", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.ConsentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("ConsentedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ExplicitConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConsentedAt");

                    b.HasIndex("DocumentVersionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "DocumentVersionId")
                        .IsUnique();

                    b.HasIndex("UserId", "ExplicitConsent", "ConsentedAt");

                    b.ToTable("consent_records", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.ContactField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProfileId", "Visibility");

                    b.ToTable("contact_fields", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.DocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangesSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LegalDocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresReConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CommitSha");

                    b.HasIndex("EffectiveFrom");

                    b.HasIndex("LegalDocumentId");

                    b.ToTable("document_versions", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.EventParticipation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant?>("CheckedInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("DeclaredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Year")
                        .IsUnique();

                    b.ToTable("event_participations", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.EventSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BarriosEarlyEntryAllocation")
                        .HasColumnType("jsonb");

                    b.Property<int>("BuildStartOffset")
                        .HasColumnType("integer");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EarlyEntryCapacity")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Instant?>("EarlyEntryClose")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventEndOffset")
                        .HasColumnType("integer");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("FinishingWeekendStartOffset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-4);

                    b.Property<int>("FirstCrewStartOffset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-25);

                    b.Property<LocalDate>("GateOpeningDate")
                        .HasColumnType("date");

                    b.Property<int?>("GlobalVolunteerCap")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShiftBrowsingOpen")
                        .HasColumnType("boolean");

                    b.Property<int>("PreEventWeekStartOffset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-9);

                    b.Property<int>("ReminderLeadTimeHours")
                        .HasColumnType("integer");

                    b.Property<int>("SetupWeekStartOffset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-16);

                    b.Property<int>("StrikeEndOffset")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("event_settings", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.GateScanEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdmitDedupeKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Instant?>("ClientScanAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuestUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LaneId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OverrideByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScannedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TicketAttendeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("AdmitDedupeKey")
                        .IsUnique()
                        .HasDatabaseName("ix_gate_scan_events_admit_dedupe_key");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("ScannedByUserId");

                    b.ToTable("gate_scan_events", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.GateSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<Instant>("GeneralEntryOpensAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinorAgeThresholdYears")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("gate_settings", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.GateStaffPin", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AdminEnrolled")
                        .HasColumnType("boolean");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("gate_staff_pins", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.GeneralAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("AvailableDayOffsets")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventSettingsId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventSettingsId");

                    b.HasIndex("UserId", "EventSettingsId")
                        .IsUnique();

                    b.ToTable("general_availability", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.LegalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentCommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("GitHubFolderPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("GracePeriodDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(7);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Instant>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("TeamId", "IsActive");

                    b.ToTable("legal_documents", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("AllergyOtherText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Bio")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("BoardNotes")
                        .HasColumnType("text");

                    b.Property<string>("BurnerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("City")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Instant?>("ConsentCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConsentCheckNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ConsentCheckStatus")
                        .HasColumnType("text");

                    b.Property<Guid?>("ConsentCheckedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContributionInterests")
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<LocalDate?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DietaryPreference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EmergencyContactRelationship")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Iban")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("IntoleranceOtherText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Intolerances")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("MedicalConditions")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("MembershipTier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Volunteer");

                    b.Property<bool>("NoPriorBurnExperience")
                        .HasColumnType("boolean");

                    b.Property<string>("PlaceId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ProfilePictureContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Pronouns")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Instant?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConsentCheckStatus");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.ProfileLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Proficiency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("profile_languages", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.Rota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("EventSettingsId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVisibleToVolunteers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PracticalInfo")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventSettingsId", "TeamId");

                    b.ToTable("rotas", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AdminOnly")
                        .HasColumnType("boolean");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOffset")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxVolunteers")
                        .HasColumnType("integer");

                    b.Property<int>("MinVolunteers")
                        .HasColumnType("integer");

                    b.Property<Guid>("RotaId")
                        .HasColumnType("uuid");

                    b.Property<LocalTime>("StartTime")
                        .HasColumnType("time");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RotaId");

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.ShiftSignup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enrolled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("EnrolledByUserId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SignupBlockId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("SignupBlockId");

                    b.HasIndex("UserId");

                    b.HasIndex("ShiftId", "Status");

                    b.ToTable("shift_signups", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.ShiftTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_shift_tags_name_unique");

                    b.ToTable("shift_tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            Name = "Heavy lifting"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            Name = "Working in the sun"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            Name = "Working in the shade"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000004"),
                            Name = "Organisational task"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000005"),
                            Name = "Meeting new people"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000006"),
                            Name = "Looking after folks"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000007"),
                            Name = "Exploring the site"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000008"),
                            Name = "Feeding and hydrating folks"
                        });
                });

            modelBuilder.Entity("Humans.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallsToAction")
                        .HasColumnType("jsonb");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomSlug")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("EarlyEntryEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("GoogleGroupPrefix")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("HasBudget")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPromotedToDirectory")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublicPage")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PageContent")
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<Instant?>("PageContentUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PageContentUpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentTeamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresApproval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ShowCoordinatorsOnPublicPage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SystemTeamType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomSlug")
                        .IsUnique()
                        .HasFilter("\"CustomSlug\" IS NOT NULL");

                    b.HasIndex("GoogleGroupPrefix")
                        .IsUnique()
                        .HasFilter("\"GoogleGroupPrefix\" IS NOT NULL");

                    b.HasIndex("IsActive");

                    b.HasIndex("ParentTeamId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("SystemTeamType");

                    b.ToTable("teams", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L),
                            Description = "All active volunteers with signed required documents",
                            EarlyEntryEnabled = false,
                            HasBudget = false,
                            IsActive = true,
                            IsHidden = false,
                            IsPromotedToDirectory = false,
                            IsPublicPage = false,
                            IsSensitive = false,
                            Name = "Volunteers",
                            RequiresApproval = false,
                            ShowCoordinatorsOnPublicPage = true,
                            Slug = "volunteers",
                            SystemTeamType = "Volunteers",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L),
                            Description = "All team coordinators",
                            EarlyEntryEnabled = false,
                            HasBudget = false,
                            IsActive = true,
                            IsHidden = false,
                            IsPromotedToDirectory = false,
                            IsPublicPage = false,
                            IsSensitive = false,
                            Name = "Coordinators",
                            RequiresApproval = false,
                            ShowCoordinatorsOnPublicPage = true,
                            Slug = "coordinators",
                            SystemTeamType = "Coordinators",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L),
                            Description = "Board members with active role assignments",
                            EarlyEntryEnabled = false,
                            HasBudget = false,
                            IsActive = true,
                            IsHidden = false,
                            IsPromotedToDirectory = false,
                            IsPublicPage = false,
                            IsSensitive = false,
                            Name = "Board",
                            RequiresApproval = false,
                            ShowCoordinatorsOnPublicPage = true,
                            Slug = "board",
                            SystemTeamType = "Board",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L),
                            Description = "Voting members with approved asociado applications",
                            EarlyEntryEnabled = false,
                            HasBudget = false,
                            IsActive = true,
                            IsHidden = false,
                            IsPromotedToDirectory = false,
                            IsPublicPage = false,
                            IsSensitive = false,
                            Name = "Asociados",
                            RequiresApproval = false,
                            ShowCoordinatorsOnPublicPage = true,
                            Slug = "asociados",
                            SystemTeamType = "Asociados",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L),
                            Description = "Active contributors with approved colaborador applications",
                            EarlyEntryEnabled = false,
                            HasBudget = false,
                            IsActive = true,
                            IsHidden = false,
                            IsPromotedToDirectory = false,
                            IsPublicPage = false,
                            IsSensitive = false,
                            Name = "Colaboradors",
                            RequiresApproval = false,
                            ShowCoordinatorsOnPublicPage = true,
                            Slug = "colaboradors",
                            SystemTeamType = "Colaboradors",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000006"),
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L),
                            Description = "All active camp leads across all camps",
                            EarlyEntryEnabled = false,
                            HasBudget = false,
                            IsActive = true,
                            IsHidden = false,
                            IsPromotedToDirectory = false,
                            IsPublicPage = false,
                            IsSensitive = false,
                            Name = "Barrio Leads",
                            RequiresApproval = false,
                            ShowCoordinatorsOnPublicPage = true,
                            Slug = "barrio-leads",
                            SystemTeamType = "BarrioLeads",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L)
                        });
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamEarlyEntryGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<LocalDate>("EntryDate")
                        .HasColumnType("date");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("team_early_entry_grants", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamJoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Instant>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "UserId", "Status");

                    b.ToTable("team_join_requests", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamJoinRequestStateHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TeamJoinRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("TeamJoinRequestId");

                    b.ToTable("team_join_request_state_history", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Role");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_team_members_active_unique")
                        .HasFilter("\"LeftAt\" IS NULL");

                    b.ToTable("team_members", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamRoleDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamMemberId");

                    b.HasIndex("TeamRoleDefinitionId", "SlotIndex")
                        .IsUnique()
                        .HasDatabaseName("IX_team_role_assignments_definition_slot_unique");

                    b.HasIndex("TeamRoleDefinitionId", "TeamMemberId")
                        .IsUnique()
                        .HasDatabaseName("IX_team_role_assignments_definition_member_unique");

                    b.ToTable("team_role_assignments", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamRoleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("EstimatedHours")
                        .HasColumnType("integer");

                    b.Property<bool>("IsManagement")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Priorities")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValueSql("''");

                    b.Property<int>("SlotCount")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_team_role_definitions_team_name_unique");

                    b.ToTable("team_role_definitions", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("ContactSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("DeletionEligibleAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("DeletionRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("DeletionScheduledFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ExternalSourceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GoogleEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("GoogleEmail");

                    b.Property<string>("GoogleEmailStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Unknown");

                    b.Property<Guid?>("ICalToken")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("LastConsentReminderSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("MagicLinkSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("MergedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MergedToUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("SuppressScheduleChangeEmails")
                        .HasColumnType("boolean");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("UnsubscribedFromCampaigns")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("MergedToUserId")
                        .HasFilter("\"MergedToUserId\" IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("ContactSource", "ExternalSourceId")
                        .HasFilter("\"ExternalSourceId\" IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.UserEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GoogleEmailStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Unknown");

                    b.Property<bool>("IsGoogle")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOAuth")
                        .HasColumnType("boolean")
                        .HasColumnName("IsOAuth");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("IsNotificationTarget");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("VerificationSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Visibility")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"IsVerified\" = true");

                    b.HasIndex("UserId");

                    b.ToTable("user_emails", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.VolunteerBuildStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<LocalDate?>("BarrioSetupStartDate")
                        .HasColumnType("date");

                    b.Property<string>("DayOffs")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Guid>("EventSettingsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Instant?>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SetByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventSettingsId");

                    b.HasIndex("UserId", "EventSettingsId")
                        .IsUnique();

                    b.ToTable("volunteer_build_statuses", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.VolunteerEventProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("AllergyOtherText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DietaryPreference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IntoleranceOtherText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Intolerances")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MedicalConditions")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Quirks")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("volunteer_event_profiles", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.VolunteerHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<LocalDate>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("volunteer_history_entries", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.VolunteerTagPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShiftTagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShiftTagId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ShiftTagId")
                        .IsUnique()
                        .HasDatabaseName("IX_volunteer_tag_preferences_user_tag_unique");

                    b.ToTable("volunteer_tag_preferences", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("RotaShiftTag", b =>
                {
                    b.Property<Guid>("RotaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShiftTagId")
                        .HasColumnType("uuid");

                    b.HasKey("RotaId", "ShiftTagId");

                    b.HasIndex("ShiftTagId");

                    b.ToTable("rota_shift_tags", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.AccountMergeRequest", b =>
                {
                    b.HasOne("Humans.Domain.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Humans.Domain.Entities.User", "SourceUser")
                        .WithMany()
                        .HasForeignKey("SourceUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Humans.Domain.Entities.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResolvedByUser");

                    b.Navigation("SourceUser");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Humans.Domain.Entities.CommunicationPreference", b =>
                {
                    b.HasOne("Humans.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Humans.Domain.Entities.ConsentRecord", b =>
                {
                    b.HasOne("Humans.Domain.Entities.DocumentVersion", "DocumentVersion")
                        .WithMany("ConsentRecords")
                        .HasForeignKey("DocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentVersion");
                });

            modelBuilder.Entity("Humans.Domain.Entities.ContactField", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Profile", "Profile")
                        .WithMany("ContactFields")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Humans.Domain.Entities.DocumentVersion", b =>
                {
                    b.HasOne("Humans.Domain.Entities.LegalDocument", "LegalDocument")
                        .WithMany("Versions")
                        .HasForeignKey("LegalDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegalDocument");
                });

            modelBuilder.Entity("Humans.Domain.Entities.EventParticipation", b =>
                {
                    b.HasOne("Humans.Domain.Entities.User", null)
                        .WithMany("EventParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Humans.Domain.Entities.GeneralAvailability", b =>
                {
                    b.HasOne("Humans.Domain.Entities.EventSettings", "EventSettings")
                        .WithMany()
                        .HasForeignKey("EventSettingsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventSettings");
                });

            modelBuilder.Entity("Humans.Domain.Entities.Profile", b =>
                {
                    b.HasOne("Humans.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Humans.Domain.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Humans.Domain.Entities.ProfileLanguage", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Profile", "Profile")
                        .WithMany("Languages")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Humans.Domain.Entities.Rota", b =>
                {
                    b.HasOne("Humans.Domain.Entities.EventSettings", "EventSettings")
                        .WithMany("Rotas")
                        .HasForeignKey("EventSettingsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventSettings");
                });

            modelBuilder.Entity("Humans.Domain.Entities.Shift", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Rota", "Rota")
                        .WithMany("Shifts")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("Humans.Domain.Entities.ShiftSignup", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Shift", "Shift")
                        .WithMany("ShiftSignups")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Humans.Domain.Entities.Team", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Team", "ParentTeam")
                        .WithMany("ChildTeams")
                        .HasForeignKey("ParentTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentTeam");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamEarlyEntryGrant", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Team", "Team")
                        .WithMany("EarlyEntryGrants")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamJoinRequest", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Team", "Team")
                        .WithMany("JoinRequests")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamJoinRequestStateHistory", b =>
                {
                    b.HasOne("Humans.Domain.Entities.TeamJoinRequest", "TeamJoinRequest")
                        .WithMany("StateHistory")
                        .HasForeignKey("TeamJoinRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamJoinRequest");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamRoleAssignment", b =>
                {
                    b.HasOne("Humans.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Humans.Domain.Entities.TeamRoleDefinition", "TeamRoleDefinition")
                        .WithMany("Assignments")
                        .HasForeignKey("TeamRoleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamMember");

                    b.Navigation("TeamRoleDefinition");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamRoleDefinition", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Team", "Team")
                        .WithMany("RoleDefinitions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Humans.Domain.Entities.User", b =>
                {
                    b.HasOne("Humans.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("MergedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Humans.Domain.Entities.UserEmail", b =>
                {
                    b.HasOne("Humans.Domain.Entities.User", null)
                        .WithMany("UserEmails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Humans.Domain.Entities.VolunteerBuildStatus", b =>
                {
                    b.HasOne("Humans.Domain.Entities.EventSettings", null)
                        .WithMany()
                        .HasForeignKey("EventSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Humans.Domain.Entities.VolunteerHistoryEntry", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Profile", "Profile")
                        .WithMany("VolunteerHistory")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Humans.Domain.Entities.VolunteerTagPreference", b =>
                {
                    b.HasOne("Humans.Domain.Entities.ShiftTag", "ShiftTag")
                        .WithMany("VolunteerPreferences")
                        .HasForeignKey("ShiftTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShiftTag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Humans.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Humans.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Humans.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Humans.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotaShiftTag", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Rota", null)
                        .WithMany()
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Humans.Domain.Entities.ShiftTag", null)
                        .WithMany()
                        .HasForeignKey("ShiftTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Humans.Domain.Entities.DocumentVersion", b =>
                {
                    b.Navigation("ConsentRecords");
                });

            modelBuilder.Entity("Humans.Domain.Entities.EventSettings", b =>
                {
                    b.Navigation("Rotas");
                });

            modelBuilder.Entity("Humans.Domain.Entities.LegalDocument", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Humans.Domain.Entities.Profile", b =>
                {
                    b.Navigation("ContactFields");

                    b.Navigation("Languages");

                    b.Navigation("VolunteerHistory");
                });

            modelBuilder.Entity("Humans.Domain.Entities.Rota", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Humans.Domain.Entities.Shift", b =>
                {
                    b.Navigation("ShiftSignups");
                });

            modelBuilder.Entity("Humans.Domain.Entities.ShiftTag", b =>
                {
                    b.Navigation("VolunteerPreferences");
                });

            modelBuilder.Entity("Humans.Domain.Entities.Team", b =>
                {
                    b.Navigation("ChildTeams");

                    b.Navigation("EarlyEntryGrants");

                    b.Navigation("JoinRequests");

                    b.Navigation("Members");

                    b.Navigation("RoleDefinitions");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamJoinRequest", b =>
                {
                    b.Navigation("StateHistory");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamMember", b =>
                {
                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamRoleDefinition", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Humans.Domain.Entities.User", b =>
                {
                    b.Navigation("EventParticipations");

                    b.Navigation("UserEmails");
                });
#pragma warning restore 612, 618
        }
    }
}
