// <auto-generated />
using System;
using Humans.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Humans.Infrastructure.Migrations.Email
{
    [DbContext(typeof(EmailDbContext))]
    [Migration("20260809032650_BaselineEmail")]
    partial class BaselineEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Humans.Domain.Entities.EmailOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CampaignGrantId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtraHeaders")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Instant?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlainTextBody")
                        .HasColumnType("text");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReplyTo")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<Instant?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ShiftSignupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CampaignGrantId");

                    b.HasIndex("UserId");

                    b.HasIndex("ShiftSignupId", "TemplateName")
                        .HasFilter("\"ShiftSignupId\" IS NOT NULL");

                    b.HasIndex("SentAt", "RetryCount", "NextRetryAt", "PickedUpAt");

                    b.ToTable("email_outbox_messages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
