namespace Humans.Domain.Enums;

/// <summary>
/// Actions that can be recorded in the audit log.
/// Stored as string in DB; new values can be appended without migration.
/// </summary>
public enum AuditAction
{
    TeamMemberAdded,
    TeamMemberRemoved,
    MemberSuspended,
    MemberUnsuspended,
    AccountAnonymized,
    RoleAssigned,
    RoleEnded,
    VolunteerApproved,
    GoogleResourceAccessGranted,
    GoogleResourceAccessRevoked,
    GoogleResourceProvisioned,
    TeamJoinedDirectly,
    TeamLeft,
    TeamJoinRequestApproved,
    TeamJoinRequestRejected,
    TeamMemberRoleChanged,
    AnomalousPermissionDetected,
    MembershipsRevokedOnDeletionRequest,
    ConsentCheckCleared,
    ConsentCheckFlagged,
    SignupRejected,
    TierApplicationApproved,
    TierApplicationRejected,
    TierDowngraded,
    GoogleResourceDeactivated,
    FacilitatedMessageSent,
    TeamRoleDefinitionCreated,
    TeamRoleDefinitionUpdated,
    TeamRoleDefinitionDeleted,
    TeamRoleAssigned,
    TeamRoleUnassigned,
    CampCreated,
    CampUpdated,
    CampDeleted,
    CampSeasonCreated,
    CampSeasonApproved,
    CampSeasonRejected,
    CampSeasonWithdrawn,
    CampSeasonStatusChanged,
    CampNameChanged,
    CampLeadAdded,
    CampLeadRemoved,
    CampPrimaryLeadTransferred,
    CampImageUploaded,
    CampImageDeleted,
    ShiftSignupConfirmed,
    ShiftSignupRefused,
    ShiftSignupVoluntold,
    ShiftSignupBailed,
    ShiftSignupNoShow,
    ShiftSignupCancelled,
    TeamPageContentUpdated,
    FeedbackResponseSent,
    FeedbackStatusChanged,
    WorkspaceAccountProvisioned,
    WorkspaceAccountSuspended,
    WorkspaceAccountReactivated,
    WorkspaceAccountPasswordReset,
    WorkspaceAccountLinked,
    AccountMergeRequested,
    AccountMergeAccepted,
    AccountMergeRejected,
    GoogleResourceSettingsRemediated,
    CommunicationPreferenceChanged,
    ContactCreated,
    RotaMovedToTeam,
}
