// <auto-generated />
using System;
using Humans.CityPlanning.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Humans.CityPlanning.Data.Migrations
{
    [DbContext(typeof(CityPlanningDbContext))]
    [Migration("20260809142312_BaselineCityPlanning")]
    partial class BaselineCityPlanning
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Humans.Domain.Entities.CampPolygon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AreaSqm")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CampSeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("GeoJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastModifiedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CampSeasonId")
                        .IsUnique();

                    b.ToTable("camp_polygons", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.CampPolygonHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AreaSqm")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CampSeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("GeoJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("CampSeasonId", "ModifiedAt");

                    b.ToTable("camp_polygon_histories", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.CityPlanningSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("ContainerPlacementClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("ContainerPlacementOpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsContainerPlacementOpen")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPlacementOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("LimitZoneGeoJson")
                        .HasColumnType("text");

                    b.Property<string>("OfficialZonesGeoJson")
                        .HasColumnType("text");

                    b.Property<Instant?>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<LocalDateTime?>("PlacementClosesAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<LocalDateTime?>("PlacementOpensAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RegistrationInfo")
                        .HasColumnType("text");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("city_planning_settings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
