// <auto-generated />
using System;
using Humans.Expenses.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Humans.Expenses.Data.Migrations
{
    [DbContext(typeof(ExpensesDbContext))]
    [Migration("20260821025435_VendorCommitments")]
    partial class VendorCommitments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Humans.Expenses.Domain.ExpenseAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Instant?>("HoldedUploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Instant>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("expense_attachments", (string)null);
                });

            modelBuilder.Entity("Humans.Expenses.Domain.ExpenseLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ExpenseReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Receipt");

                    b.Property<Guid?>("ParentLineId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("ExpenseReportId");

                    b.HasIndex("ParentLineId");

                    b.ToTable("expense_lines", (string)null);
                });

            modelBuilder.Entity("Humans.Expenses.Domain.ExpenseReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetYearId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("CoordinatorEndorsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CoordinatorEndorsedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HoldedContactId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("HoldedDocId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("HoldedSupplierAccountNum")
                        .HasColumnType("integer");

                    b.Property<Instant?>("LastRejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastRejectedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastRejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("MaxAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PayeeIban")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("PayeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Instant?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubmitterUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BudgetCategoryId");

                    b.HasIndex("HoldedContactId");

                    b.HasIndex("HoldedDocId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmitterUserId", "Status");

                    b.ToTable("expense_reports", (string)null);
                });

            modelBuilder.Entity("Humans.Expenses.Domain.HoldedExpenseOutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ExpenseReportId")
                        .HasColumnType("uuid");

                    b.Property<bool>("FailedPermanently")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Instant?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseReportId");

                    b.HasIndex("ProcessedAt", "FailedPermanently");

                    b.ToTable("holded_expense_outbox_events", (string)null);
                });

            modelBuilder.Entity("Humans.Expenses.Domain.VendorCommitment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BudgetCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("ExpectedAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("HoldedContactId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Instant?>("MatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MatchedHoldedDocId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("MatchedHoldedDocNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("QuoteContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("QuoteExtension")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("QuoteFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Instant?>("QuoteUploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BudgetCategoryId");

                    b.HasIndex("HoldedContactId");

                    b.HasIndex("MatchedHoldedDocId");

                    b.HasIndex("Status");

                    b.ToTable("vendor_commitments", (string)null);
                });

            modelBuilder.Entity("Humans.Expenses.Domain.VendorCommitmentMatchCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("Accepted")
                        .HasColumnType("boolean");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Instant>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<LocalDate>("DocDate")
                        .HasColumnType("date");

                    b.Property<decimal>("DocTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("HoldedDocId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("HoldedDocNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Instant?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VendorCommitmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedAt");

                    b.HasIndex("VendorCommitmentId", "HoldedDocId")
                        .IsUnique();

                    b.ToTable("vendor_commitment_match_candidates", (string)null);
                });

            modelBuilder.Entity("Humans.Expenses.Domain.VendorCommitmentPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<LocalDate>("PaidOn")
                        .HasColumnType("date");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("VendorCommitmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendorCommitmentId");

                    b.ToTable("vendor_commitment_payments", (string)null);
                });

            modelBuilder.Entity("Humans.Expenses.Domain.ExpenseLine", b =>
                {
                    b.HasOne("Humans.Expenses.Domain.ExpenseAttachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Humans.Expenses.Domain.ExpenseReport", null)
                        .WithMany("Lines")
                        .HasForeignKey("ExpenseReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Humans.Expenses.Domain.ExpenseLine", null)
                        .WithMany()
                        .HasForeignKey("ParentLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("Humans.Expenses.Domain.VendorCommitmentMatchCandidate", b =>
                {
                    b.HasOne("Humans.Expenses.Domain.VendorCommitment", "Commitment")
                        .WithMany("MatchCandidates")
                        .HasForeignKey("VendorCommitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commitment");
                });

            modelBuilder.Entity("Humans.Expenses.Domain.VendorCommitmentPayment", b =>
                {
                    b.HasOne("Humans.Expenses.Domain.VendorCommitment", "Commitment")
                        .WithMany("Payments")
                        .HasForeignKey("VendorCommitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commitment");
                });

            modelBuilder.Entity("Humans.Expenses.Domain.ExpenseReport", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Humans.Expenses.Domain.VendorCommitment", b =>
                {
                    b.Navigation("MatchCandidates");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
