// <auto-generated />
using System;
using Humans.Teams.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Humans.Teams.Data.Migrations
{
    [DbContext(typeof(TeamsDbContext))]
    partial class TeamsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Humans.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallsToAction")
                        .HasColumnType("jsonb");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomSlug")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("EarlyEntryEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("GoogleGroupPrefix")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("HasBudget")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPromotedToDirectory")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublicPage")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PageContent")
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<Instant?>("PageContentUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PageContentUpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentTeamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresApproval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ShowCoordinatorsOnPublicPage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SystemTeamType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomSlug")
                        .IsUnique()
                        .HasFilter("\"CustomSlug\" IS NOT NULL");

                    b.HasIndex("GoogleGroupPrefix")
                        .IsUnique()
                        .HasFilter("\"GoogleGroupPrefix\" IS NOT NULL");

                    b.HasIndex("IsActive");

                    b.HasIndex("ParentTeamId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("SystemTeamType");

                    b.ToTable("teams", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L),
                            Description = "All active volunteers with signed required documents",
                            EarlyEntryEnabled = false,
                            HasBudget = false,
                            IsActive = true,
                            IsHidden = false,
                            IsPromotedToDirectory = false,
                            IsPublicPage = false,
                            IsSensitive = false,
                            Name = "Volunteers",
                            RequiresApproval = false,
                            ShowCoordinatorsOnPublicPage = true,
                            Slug = "volunteers",
                            SystemTeamType = "Volunteers",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L),
                            Description = "All team coordinators",
                            EarlyEntryEnabled = false,
                            HasBudget = false,
                            IsActive = true,
                            IsHidden = false,
                            IsPromotedToDirectory = false,
                            IsPublicPage = false,
                            IsSensitive = false,
                            Name = "Coordinators",
                            RequiresApproval = false,
                            ShowCoordinatorsOnPublicPage = true,
                            Slug = "coordinators",
                            SystemTeamType = "Coordinators",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L),
                            Description = "Board members with active role assignments",
                            EarlyEntryEnabled = false,
                            HasBudget = false,
                            IsActive = true,
                            IsHidden = false,
                            IsPromotedToDirectory = false,
                            IsPublicPage = false,
                            IsSensitive = false,
                            Name = "Board",
                            RequiresApproval = false,
                            ShowCoordinatorsOnPublicPage = true,
                            Slug = "board",
                            SystemTeamType = "Board",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L),
                            Description = "Voting members with approved asociado applications",
                            EarlyEntryEnabled = false,
                            HasBudget = false,
                            IsActive = true,
                            IsHidden = false,
                            IsPromotedToDirectory = false,
                            IsPublicPage = false,
                            IsSensitive = false,
                            Name = "Asociados",
                            RequiresApproval = false,
                            ShowCoordinatorsOnPublicPage = true,
                            Slug = "asociados",
                            SystemTeamType = "Asociados",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L),
                            Description = "Active contributors with approved colaborador applications",
                            EarlyEntryEnabled = false,
                            HasBudget = false,
                            IsActive = true,
                            IsHidden = false,
                            IsPromotedToDirectory = false,
                            IsPublicPage = false,
                            IsSensitive = false,
                            Name = "Colaboradors",
                            RequiresApproval = false,
                            ShowCoordinatorsOnPublicPage = true,
                            Slug = "colaboradors",
                            SystemTeamType = "Colaboradors",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000006"),
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L),
                            Description = "All active camp leads across all camps",
                            EarlyEntryEnabled = false,
                            HasBudget = false,
                            IsActive = true,
                            IsHidden = false,
                            IsPromotedToDirectory = false,
                            IsPublicPage = false,
                            IsSensitive = false,
                            Name = "Barrio Leads",
                            RequiresApproval = false,
                            ShowCoordinatorsOnPublicPage = true,
                            Slug = "barrio-leads",
                            SystemTeamType = "BarrioLeads",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17702491570000000L)
                        });
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamEarlyEntryGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<LocalDate>("EntryDate")
                        .HasColumnType("date");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("team_early_entry_grants", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamJoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Instant>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "UserId", "Status");

                    b.ToTable("team_join_requests", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamJoinRequestStateHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TeamJoinRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("TeamJoinRequestId");

                    b.ToTable("team_join_request_state_history", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Instant?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Role");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_team_members_active_unique")
                        .HasFilter("\"LeftAt\" IS NULL");

                    b.ToTable("team_members", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamRoleDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamMemberId");

                    b.HasIndex("TeamRoleDefinitionId", "SlotIndex")
                        .IsUnique()
                        .HasDatabaseName("IX_team_role_assignments_definition_slot_unique");

                    b.HasIndex("TeamRoleDefinitionId", "TeamMemberId")
                        .IsUnique()
                        .HasDatabaseName("IX_team_role_assignments_definition_member_unique");

                    b.ToTable("team_role_assignments", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamRoleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("EstimatedHours")
                        .HasColumnType("integer");

                    b.Property<bool>("IsManagement")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Priorities")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValueSql("''");

                    b.Property<int>("SlotCount")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_team_role_definitions_team_name_unique");

                    b.ToTable("team_role_definitions", (string)null);
                });

            modelBuilder.Entity("Humans.Domain.Entities.Team", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Team", "ParentTeam")
                        .WithMany("ChildTeams")
                        .HasForeignKey("ParentTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentTeam");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamEarlyEntryGrant", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Team", "Team")
                        .WithMany("EarlyEntryGrants")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamJoinRequest", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Team", "Team")
                        .WithMany("JoinRequests")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamJoinRequestStateHistory", b =>
                {
                    b.HasOne("Humans.Domain.Entities.TeamJoinRequest", "TeamJoinRequest")
                        .WithMany("StateHistory")
                        .HasForeignKey("TeamJoinRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamJoinRequest");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamRoleAssignment", b =>
                {
                    b.HasOne("Humans.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Humans.Domain.Entities.TeamRoleDefinition", "TeamRoleDefinition")
                        .WithMany("Assignments")
                        .HasForeignKey("TeamRoleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamMember");

                    b.Navigation("TeamRoleDefinition");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamRoleDefinition", b =>
                {
                    b.HasOne("Humans.Domain.Entities.Team", "Team")
                        .WithMany("RoleDefinitions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Humans.Domain.Entities.Team", b =>
                {
                    b.Navigation("ChildTeams");

                    b.Navigation("EarlyEntryGrants");

                    b.Navigation("JoinRequests");

                    b.Navigation("Members");

                    b.Navigation("RoleDefinitions");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamJoinRequest", b =>
                {
                    b.Navigation("StateHistory");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamMember", b =>
                {
                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("Humans.Domain.Entities.TeamRoleDefinition", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
